# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # at 00:00 UTC every day
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SUMMARY_GITHUB_TOKEN }}

          # Options
          user: Youxingz
          template: classic
          base: header, activity, community, metadata
          config_padding: 0, 14%
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_from: user
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          repositories_affiliations: owner, collaborator
